# Generated by Django 3.0.6 on 2020-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('gb_id', models.PositiveIntegerField(unique=True, verbose_name='Giant Bomb ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('gb_id', models.PositiveIntegerField(unique=True, verbose_name='Giant Bomb ID')),
                ('name', models.CharField(max_length=100)),
                ('site_url', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('gb_id', models.PositiveIntegerField(unique=True, verbose_name='Giant Bomb ID')),
                ('name', models.CharField(max_length=100)),
                ('site_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('deck', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('gb_id', models.PositiveIntegerField(unique=True, verbose_name='Giant Bomb ID')),
                ('name', models.CharField(max_length=100)),
                ('site_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('deck', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('gb_id', models.PositiveIntegerField(unique=True, verbose_name='Giant Bomb ID')),
                ('name', models.CharField(max_length=100)),
                ('site_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('deck', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('gb_id', models.PositiveIntegerField(unique=True, verbose_name='Giant Bomb ID')),
                ('name', models.CharField(max_length=100)),
                ('site_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('abbreviation', models.CharField(max_length=20)),
                ('deck', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('gb_id', models.PositiveIntegerField(unique=True, verbose_name='Giant Bomb ID')),
                ('name', models.CharField(max_length=100)),
                ('site_url', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
