# Generated by Django 3.0.6 on 2020-07-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgl', '0002_agerating_company_concept_franchise_genre_platform_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='deck',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='deck',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='deck',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='deck',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
