# Generated by Django 3.0.6 on 2020-12-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgl', '0003_auto_20200724_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('game_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('players', models.PositiveIntegerField(default=0)),
                ('mean_rating', models.FloatField(default=0)),
            ],
        ),
    ]
