# Generated by Django 3.0.6 on 2020-12-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgl', '0004_gamestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='als_user_id',
            field=models.PositiveIntegerField(default=11347171, unique=True),
            preserve_default=False,
        ),
    ]
